### PR TITLE
Added support to numbers

### PR DESCRIPTION
**Pull request by AndreLobato**
Fix issue #1

### CODE REVIEW

**Comment by AndreLobato** [comment]
Implement day support #2  on the following commit, let me know if have interest to have any of the features separated

**Comment by AndreLobato** [comment]
Any reason to not accept this PR?

**Comment by utgwkk** [comment]
@AndreLobato I'm very sorry I missed it. Please resolve conflicts, and I will merge it immediately.

**Comment by utgwkk** [comment]
Thank you!

**Pull request merged**
